#!/usr/bin/env bash

# https://github.com/tommarshall/git-good-commit
# git-good-commit(1) - Git hook to help you write good commit messages.
#
# Released under the MIT License.
# The MIT License (MIT)
#
# Copyright (c) 2016 Tom Marshall
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

COMMIT_MSG_FILE="$1"
COMMIT_MSG_LINES=
COMMIT_MSG=$(<"$COMMIT_MSG_FILE")
SKIP_DISPLAY_WARNINGS=0
WARNINGS=
ERRORS=

RED=
YELLOW=
BLUE=
WHITE=
NC=

# Skip if commit message starts with 'Merge'
[[ "$COMMIT_MSG" =~ ^Merge ]] && exit 0

BRANCH_NAME=$(git symbolic-ref --short HEAD)
MASTER_REGEX='^(:?main|master)$'
HOTFIX_REGEX='^(\[[Hh][Ff]\]|[hH]otfix)'
MATCH_BRANCH_NUMBER=$(git config --bool --get hooks.goodcommit.matchBranchNumber || echo false)

# Main branch exception: if branch is main and message starts with hotfix
[[ "$BRANCH_NAME" =~ $MASTER_REGEX ]] && [[ "$COMMIT_MSG" =~ $HOTFIX_REGEX ]] && exit 0

#
# Set colour variables if the output should be coloured.
#

set_colors() {
  local default_color
  default_color=$(git config --get hooks.goodcommit.color || git config --get color.ui || echo 'auto')
  if [[ $default_color == 'always' ]] || [[ $default_color == 'auto' && -t 1 ]]; then
    RED='\033[1;31m'
    YELLOW='\033[1;33m'
    BLUE='\033[1;34m'
    WHITE='\033[1;37m'
    NC='\033[0m' # No Color
  fi
}

#
# Output prompt help information.
#

prompt_help() {
  echo -e "${RED}$(
    cat <<-EOF
e - edit commit message
y - proceed with commit
n - abort commit
? - print help
EOF
  )${NC}"
}

#
# Add a warning with <line_number> and <msg>.
#

add_warning() {
  local line_number=$1
  local warning=$2
  WARNINGS[line_number]="${WARNINGS[$line_number]}$warning;"
}

add_error() {
  local line_number=$1
  local error=$2
  ERRORS[line_number]="${ERRORS[$line_number]}$error;"
}

#
# Output warnings.
#

display_warnings() {
  for i in "${!ERRORS[@]}"; do
    printf "%-74s ${WHITE}%s${NC}\n" "${COMMIT_MSG_LINES[$((i - 1))]}" "[line ${i}]"
    IFS=';' read -ra ERRORS_ARRAY <<<"${ERRORS[$i]}"
    for ERROR in "${ERRORS_ARRAY[@]}"; do
      echo -e " ${RED}- ${ERROR}${NC}"
    done
  done

  if [ $SKIP_DISPLAY_WARNINGS -eq 1 ]; then
    # if the warnings were skipped then they should be displayed next time
    SKIP_DISPLAY_WARNINGS=0
    return
  fi

  for i in "${!WARNINGS[@]}"; do
    printf "%-74s ${WHITE}%s${NC}\n" "${COMMIT_MSG_LINES[$((i - 1))]}" "[line ${i}]"
    IFS=';' read -ra WARNINGS_ARRAY <<<"${WARNINGS[$i]}"
    for WARNING in "${WARNINGS_ARRAY[@]}"; do
      echo -e " ${YELLOW}- ${WARNING}${NC}"
    done
  done
}

#
# Read the contents of the commit msg into an array of lines.
#

read_commit_message() {
  git_failed=false
  if ! [ $? -eq 0 ]; then
    git_failed=true
  fi

  BRANCH_NUMBER_REGEX='/(:?[[:upper:]]*-)?([[:digit:]]*)[/-]'
  if [[ $BRANCH_NAME =~ $BRANCH_NUMBER_REGEX ]]; then
    BRANCH_NUMBER="${BASH_REMATCH[1]}"
  fi
  # reset commit_msg_lines
  COMMIT_MSG_LINES=()

  # read commit message into lines array
  while IFS= read -r; do

    # trim trailing spaces from commit lines
    shopt -s extglob
    REPLY="${REPLY%%*( )}"
    shopt -u extglob

    # ignore comments
    [[ $REPLY =~ ^# ]]
    test $? -eq 0 || COMMIT_MSG_LINES+=("$REPLY")

  done < <(cat "$COMMIT_MSG_FILE")
}

#
# Validate the contents of the commmit msg agains the good commit guidelines.
#

validate_commit_message() {
  # reset warnings and errors
  WARNINGS=()
  ERRORS=()

  # capture the subject, and remove the 'squash! ' prefix if present
  COMMIT_SUBJECT=${COMMIT_MSG_LINES[0]/#squash! /}

  # if the commit is empty there's nothing to validate, we can return here
  COMMIT_MSG_STR="${COMMIT_MSG_LINES[*]}"
  test -z "${COMMIT_MSG_STR[*]// /}" && return

  # if the commit subject starts with 'fixup! ' there's nothing to validate, we can return here
  [[ $COMMIT_SUBJECT == 'fixup! '* ]] && return

  # 1. Separate subject from body with a blank line
  # ------------------------------------------------------------------------------

  test ${#COMMIT_MSG_LINES[@]} -lt 1 || test -z "${COMMIT_MSG_LINES[1]}"
  test $? -eq 0 || add_warning 2 "Separate subject from body with a blank line"

  # 2. Limit the subject line to 50 characters
  # ------------------------------------------------------------------------------

  test "${#COMMIT_SUBJECT}" -le 50
  test $? -eq 0 || add_warning 1 "Limit the subject line to 50 characters (${#COMMIT_SUBJECT} chars)"

  # 3. Use issue tag at the start of the commit message
  # ------------------------------------------------------------------------------

  ISSUE_TAG_REGEX='[[:upper:]]*([# -][[:digit:]]+)|(\[[[:digit:]]+\])'
  has_issue_tag=false

  if [[ $COMMIT_SUBJECT =~ $ISSUE_TAG_REGEX ]]; then
    has_issue_tag=true
  else
    add_warning 1 "Include an issue tag in the subject line"
  fi

  ISSUE_NUMBER_REGEX="(\#$BRANCH_NUMBER)|(\[$BRANCH_NUMBER\])|(FCK-$BRANCH_NUMBER:)"

  if [[ $MATCH_BRANCH_NUMBER == true ]] && ! $git_failed; then
    [[ $COMMIT_SUBJECT =~ $ISSUE_NUMBER_REGEX ]]
    test $? -eq 0 || add_error 1 "Match issue tag with the branch number $BRANCH_NUMBER"
  fi

  # 4. Capitalize the subject line
  # ------------------------------------------------------------------------------

  if $has_issue_tag; then
    CAPITALIZE_LINE_REGEX="($ISSUE_TAG_REGEX)[:]?[[:space:]]?([[:upper:]]{1}[[:lower:]])"
  else
    CAPITALIZE_LINE_REGEX='^[[:upper:]]{1}[^[:upper:]]'
  fi

  [[ ${COMMIT_SUBJECT} =~ $CAPITALIZE_LINE_REGEX ]]
  test $? -eq 0 || add_warning 1 "Capitalize the subject line"

  # 5. Do not end the subject line with a period
  # ------------------------------------------------------------------------------

  [[ ${COMMIT_SUBJECT} =~ [^\.]$ ]]
  test $? -eq 0 || add_warning 1 "Do not end the subject line with a period"

  # 6. Use the imperative mood in the subject line
  # ------------------------------------------------------------------------------

  IMPERATIVE_MOOD_BLACKLIST=(
    added adds adding
    avoided avoids avoiding
    amended amends amending
    bumped bumps bumping
    changed changes changing
    checked checks checking
    committed commits committing
    copied copies copying
    corrected corrects correcting
    created creates creating
    deleted deletes deleting
    fixed fixes fixing
    gets getting
    implemented implements implementing
    improved improves improving
    introduced introduces introducing
    moved moves moving
    pruned prunes pruning
    refactored refactors refactoring
    removed removes removing
    renamed renames renaming
    replaced replaces replacing
    resolved resolves resolving
    showed shows showing
    tested tests testing
    updated updates updating
    used uses using
  )

  # enable case insensitive match
  shopt -s nocasematch

  for BLACKLISTED_WORD in "${IMPERATIVE_MOOD_BLACKLIST[@]}"; do
    [[ ${COMMIT_SUBJECT} =~ ^[[:blank:]]*$BLACKLISTED_WORD ]]
    test $? -eq 0 && add_warning 1 "Use the imperative mood in the subject line, e.g 'fix' not 'fixes'" && break
  done

  # disable case insensitive match
  shopt -u nocasematch

  # 7. Wrap the body at 72 characters
  # ------------------------------------------------------------------------------

  URL_REGEX='^[[:blank:]]*(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'

  for i in "${!COMMIT_MSG_LINES[@]}"; do
    LINE_NUMBER=$((i + 1))
    test "${#COMMIT_MSG_LINES[$i]}" -le 72 || [[ ${COMMIT_MSG_LINES[$i]} =~ $URL_REGEX ]]
    test $? -eq 0 || add_warning $LINE_NUMBER "Wrap the body at 72 characters (${#COMMIT_MSG_LINES[$i]} chars)"
  done

  # 8. Use the body to explain what and why vs. how
  # ------------------------------------------------------------------------------

  # ?

  # 9. Do not write single worded commits
  # ------------------------------------------------------------------------------

  COMMIT_SUBJECT_WORDS=()
  read -r -a COMMIT_SUBJECT_WORDS <<<"$COMMIT_SUBJECT"
  test "${#COMMIT_SUBJECT_WORDS[@]}" -gt 1
  test $? -eq 0 || add_warning 1 "Do not write single worded commits"

  # 10. Do not start the subject line with whitespace
  # ------------------------------------------------------------------------------

  [[ ${COMMIT_SUBJECT} =~ ^[[:blank:]]+ ]]
  test $? -eq 1 || add_warning 1 "Do not start the subject line with whitespace"
}

#
# It's showtime.
#

set_colors

while true; do

  read_commit_message

  validate_commit_message

  # if there are no WARNINGS are empty then we're good to break out of here
  test ${#WARNINGS[@]} -eq 0 && exit 0

  display_warnings

  exit 0

done
