[package]
name = "arachnobot"
version = "0.1.0"
edition = "2021"
license = "MIT"

[profile.dev]
opt-level = 0

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
staging = []

[dependencies]
poise = "^0.6.2"
regex = "^1.12.3"
serde = { version = "^1.0.228", features = ["derive"] }
tokio = { version = "^1.52.2", features = ["rt-multi-thread", "macros"] }
openssl = { version = "^0.10", features = ["vendored"] }
serde_json = "^1.0.149"
firebase-rs = "^2.2.5"
reqwest = { version = "^0.13.3", features = ["json"] }
async-trait = "^0.1.89"
dotenvy = "^0.15.7"
test-case = "^3.3.1"
tracing = "^0.1.44"
color-eyre = "^0.6.5"
tracing-subscriber = { version = "^0.3.23", features = ["fmt", "std"] }
tracing-appender = "^0.2.5"

[dev-dependencies]
mockall = "0.14.0"
