[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean", "--release"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test-prod]
command = "cargo"
args = ["test"]

[tasks.test-staging]
command = "cargo"
args = ["test", "--features=staging"]

[tasks.test]
dependencies = [
    "test-staging",
    "test-prod"
]

