[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean", "--release"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test-prod]
command = "cargo"
args = ["test"]

[tasks.test-staging]
command = "cargo"
args = ["test", "--features=staging"]

[tasks.test]
dependencies = ["test-staging", "test-prod"]

[tasks.run-staging]
command = "cargo"
args = ["run", "--features=staging"]

[tasks.dev-staging]
command = "cargo"
args = ["run", "--features=staging"]
watch = true

[tasks.check-licenses]
command = "cargo"
args = ["license", "-o", "licenses.txt"]

[tasks.check-deps]
command = "cargo"
args = ["deny", "check"]

[tasks.check]
dependencies = ["check-licenses", "check-deps"]
