on:
  workflow_call:
    outputs:
      tag:
        value: ${{ jobs.build.outputs.arch }}-${{ jobs.build.outputs.vendor }}-${{ jobs.build.outputs.os }}${{ jobs.build.outputs.environment }}
      os:
        value: ${{ jobs.build.outputs.os }}

name: Build release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: armv7
            vendor: unknown
            os: linux
            environment: -musleabihf
          - arch: x86_64
            vendor: unknown
            os: linux
            environment: -musl

    outputs:
      arch: ${{ matrix.arch }}
      vendor: ${{ matrix.vendor }}
      os: ${{ matrix.os }}
      environment: ${{ matrix.environment }}

    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: short

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up target
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.arch }}-${{ matrix.vendor }}-${{ matrix.os }}${{ matrix.environment }}
          default: true
          override: true

      - name: Cache build
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build_release"

      - name: Build release for target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.arch }}-${{ matrix.vendor }}-${{ matrix.os }}${{ matrix.environment }} --release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          name: ${{ matrix.arch }}-${{ matrix.vendor }}-${{ matrix.os }}${{ matrix.environment }}_binary
          path: |
            ./target/${{ matrix.arch }}-${{ matrix.vendor }}-${{ matrix.os }}${{ matrix.environment }}/release/arachnobot
