name: Build and test
on:
  workflow_call:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: davidB/rust-cargo-make@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache build
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build_and_test"

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo make test
