name: Build and test
on:
  workflow_call:
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache build
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'build_and_test'

      - name: Build
        run: cargo build

      - name: Compile tests
        run: cargo test --no-run

      - name: Run tests
        run: cargo test --no-fail-fast
