name: Hash latest release

on:
  workflow_dispatch:
  release:

permissions:
  contents: write

jobs:
  hash-release:
    runs-on: ubuntu-latest
    name: Publish binaries

    steps:
      - name: Generate release hashes
        uses: MCJack123/ghaction-generate-release-hashes@v3
        with:
          hash-type: sha256
          file-name: hashes.txt
      - name: Upload release hashes
        uses: svenstaro/upload-release-action@v2
        with:
          file: hashes.txt
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          asset_name: release-sha256.txt
          tag: ${{ github.ref }}
