name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  check_build_and_push:
    name: Check, build release and push to dockerhub
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  publish_release:
    name: Publish binaries
    runs-on: ubuntu-latest
    needs: [check_build_and_push]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.check_build_and_push.outputs.tag }}_binary
          path: ./release

      - name: Zip binaries
        if: needs.check_build_and_push.outputs == 'windows'
        run: zip -r ${{ needs.check_build_and_push.outputs.tag }}.zip release

      - name: Archive binaries
        if: needs.check_build_and_push.outputs != 'windows'
        run: tar zcfv ${{ needs.check_build_and_push.outputs.tag }}.tar.gz release

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./*.zip
            ./*.gz
